name: nexus_jobs
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^0.19.1
  http: ^0.12.2
  shared_preferences: ^0.5.12+2
  share: ^0.6.5+4
  simple_coverflow: ^0.0.8


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - images/logo.png
    - images/Google.svg
    - images/FB.svg
    - images/Linkedin.svg
    - images/Iconos_configuracion.svg
    - images/Iconos_Lista.svg
    - images/Iconos_Perfil.svg
    - images/Iconos_compartir.svg
  fonts:
    - family: NotoSans
      fonts:
        - asset: fonts/NotoSans-Bold.ttf
        - asset: fonts/NotoSans-BoldItalic.ttf
        - asset: fonts/NotoSans-Italic.ttf
        - asset: fonts/NotoSans-Regular.ttf

    - family: Nunito
      fonts:
        - asset: fonts/Nunito-Black.ttf
        - asset: fonts/Nunito-BlackItalic.ttf
        - asset: fonts/Nunito-Bold.ttf
        - asset: fonts/Nunito-Light.ttf
        - asset: fonts/Nunito-BoldItalic.ttf
        - asset: fonts/Nunito-ExtraBold.ttf
        - asset: fonts/Nunito-Italic.ttf
        - asset: fonts/Nunito-Regular.ttf
        - asset: fonts/Nunito-SemiBold.ttf



